version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=simone
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=master
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    networks:
      - psql
    ports:
      - "5432:5432"
volumes:
  postgres:
networks:
  psql:
    driver: bridge